# Generated by Django 5.2.7 on 2025-11-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image_url_car_featured_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
