# Generated by Django 5.2.7 on 2025-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_horsepower_car_speed_car_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
