# Generated by Django 5.2.7 on 2025-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_brand_alter_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.AddField(
            model_name='car',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
