# Generated by Django 5.2.7 on 2025-11-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_brand_car_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand'),
        ),
    ]
