# Generated by Django 5.2.7 on 2025-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(related_name='cars', to='cars.feature'),
        ),
    ]
