# Generated by Django 5.2.7 on 2025-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan')], max_length=255)),
                ('description', models.TextField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('license_plate', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('features', models.ManyToManyField(to='cars.feature')),
            ],
        ),
    ]
