# Generated by Django 5.2.7 on 2025-11-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-featured']},
        ),
    ]
