# Generated by Django 5.2.7 on 2025-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
